### ISSUE TITLE
[feature] Add support for unix domain sockets

### ISSUE THREAD

**Issue by davidchappelle** [tplgy/bonefish#2]
A new server endpoint for unix domain sockets must be added to bonefish. This should be a matter of abstracting some of the rawsocket code to accommodate different types of endpoints. Or at least abstracting the rawsocket handshake code. The example bonefish daemon should be updated to include a domain socket server endpoint. The autobahn-cpp library should also be updated to include an example using unix domain sockets.

**Comment by allspace** [comment]
Could you share more information about when to use UNIX domain socket?

**Comment by davidchappelle** [comment]
UDS are used for components that are running on the same local machine as
bonefish. When bonefish adds support for internal components UDS will be
the preferred transport type. The main benefit is increased performance as
the network stack is bypassed for UDS. Also, no UDS packets can be captured
making it secure for local communication.

Could you share more information about when to use UNIX domain socket?

**Comment by jpetso** [comment]
Dave pushed domain socket support to master as commit c435c10, so I'll go ahead and close this issue.
