### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Afra-Felix** [tplgy/bonefish#25]
I am getting a compilation error, Can any one help me in this?

[  2%] Building CXX object src/CMakeFiles/bonefish.dir/bonefish/native/native_server_impl.cpp.o
In file included from /home/user1/work/bonefish/src/bonefish/native/native_endpoint.hpp:25:0,
                 from /home/user1/work/bonefish/src/bonefish/native/native_connector.hpp:20,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.hpp:21,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.cpp:17:
/usr/include/boost/thread/future.hpp: In instantiation of 'void boost::promise<R>::set_exception(E) [with E = std::runtime_error; R = std::shared_ptrbonefish::native_endpoint]':
/home/user1/work/bonefish/src/bonefish/native/native_server_impl.cpp:66:74:   required from here
/usr/include/boost/thread/future.hpp:2092:42: error: call of overloaded 'copy_exception(std::runtime_error&)' is ambiguous
           set_exception(copy_exception(ex));
                                          ^
/usr/include/boost/thread/future.hpp:2092:42: note: candidates are:
In file included from /usr/include/boost/exception_ptr.hpp:9:0,
                 from /usr/include/boost/thread/future.hpp:28,
                 from /home/user1/work/bonefish/src/bonefish/native/native_endpoint.hpp:25,
                 from /home/user1/work/bonefish/src/bonefish/native/native_connector.hpp:20,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.hpp:21,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.cpp:17:
/usr/include/boost/exception/detail/exception_ptr.hpp:75:5: note: boost::exception_ptr boost::copy_exception(const T&) [with T = std::runtime_error]
     copy_exception( T const & e )
     ^
In file included from /usr/include/c++/4.9/exception:162:0,
                 from /usr/include/c++/4.9/typeinfo:34,
                 from /usr/include/c++/4.9/functional:53,
                 from /home/user1/work/bonefish/src/bonefish/identifiers/wamp_random_id.hpp:21,
                 from /home/user1/work/bonefish/src/bonefish/identifiers/wamp_session_id.hpp:20,
                 from /home/user1/work/bonefish/src/bonefish/common/wamp_message_processor.hpp:20,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.hpp:20,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.cpp:17:
/usr/include/c++/4.9/bits/exception_ptr.h:193:5: note: std::__exception_ptr::exception_ptr std::copy_exception(_Ex) [with _Ex = std::runtime_error]
     copy_exception(_Ex __ex) _GLIBCXX_USE_NOEXCEPT
     ^
In file included from /home/user1/work/bonefish/src/bonefish/native/native_endpoint.hpp:25:0,
                 from /home/user1/work/bonefish/src/bonefish/native/native_connector.hpp:20,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.hpp:21,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.cpp:17:
/usr/include/boost/thread/future.hpp: In instantiation of 'void boost::promise<void>::set_exception(E) [with E = std::runtime_error]':
/home/user1/work/bonefish/src/bonefish/native/native_server_impl.cpp:95:80:   required from here
/usr/include/boost/thread/future.hpp:2409:42: error: call of overloaded 'copy_exception(std::runtime_error&)' is ambiguous
           set_exception(copy_exception(ex));
                                          ^
/usr/include/boost/thread/future.hpp:2409:42: note: candidates are:
In file included from /usr/include/boost/exception_ptr.hpp:9:0,
                 from /usr/include/boost/thread/future.hpp:28,
                 from /home/user1/work/bonefish/src/bonefish/native/native_endpoint.hpp:25,
                 from /home/user1/work/bonefish/src/bonefish/native/native_connector.hpp:20,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.hpp:21,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.cpp:17:
/usr/include/boost/exception/detail/exception_ptr.hpp:75:5: note: boost::exception_ptr boost::copy_exception(const T&) [with T = std::runtime_error]
     copy_exception( T const & e )
     ^
In file included from /usr/include/c++/4.9/exception:162:0,
                 from /usr/include/c++/4.9/typeinfo:34,
                 from /usr/include/c++/4.9/functional:53,
                 from /home/user1/work/bonefish/src/bonefish/identifiers/wamp_random_id.hpp:21,
                 from /home/user1/work/bonefish/src/bonefish/identifiers/wamp_session_id.hpp:20,
                 from /home/user1/work/bonefish/src/bonefish/common/wamp_message_processor.hpp:20,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.hpp:20,
                 from /home/user1/work/bonefish/src/bonefish/native/native_server_impl.cpp:17:
/usr/include/c++/4.9/bits/exception_ptr.h:193:5: note: std::__exception_ptr::exception_ptr std::copy_exception(_Ex) [with _Ex = std::runtime_error]
     copy_exception(_Ex __ex) _GLIBCXX_USE_NOEXCEPT
     ^
src/CMakeFiles/bonefish.dir/build.make:330: recipe for target 'src/CMakeFiles/bonefish.dir/bonefish/native/native_server_impl.cpp.o' failed
make[2]: **\* [src/CMakeFiles/bonefish.dir/bonefish/native/native_server_impl.cpp.o] Error 1
CMakeFiles/Makefile2:125: recipe for target 'src/CMakeFiles/bonefish.dir/all' failed
make[1]: **\* [src/CMakeFiles/bonefish.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by davidchappelle** [comment]
Can you try replacing the set_exception(...) calls with
set_exception(boost::copy_exception(...)).

**Comment by Afra-Felix** [comment]
@davidchappelle you fix works :)

**Comment by Afra-Felix** [comment]
Thanks, I accidentally closed and commented it.
