### ISSUE TITLE
invalid array index in bonefish/messages/wamp_welcome_details.cpp

### ISSUE THREAD

**Issue by VE3RQX** [tplgy/bonefish#44]
Results in a hard crash on Windows build;  problem did not surface on Linux, nor was picked up via valgrind or similar tools.

Problem is on lines 57-61.  Array allocated for size 1 on lines 57-59, but indexed on lines 60-61 using loop iterator.  The fix is simple:  change "index" to "0".  

While I am here, is there any extant example of in-process client side use of the "native_server"?

**Comment by davidchappelle** [comment]
Nice catch. If you could put together a pull request that would be great. I
had some code that does in process calls between client and native server.
I'll see if I can find out what I did with it.

**Comment by jrogers** [comment]
pull request #45 merged

**Comment by davidchappelle** [comment]
@halflete Take a look at https://github.com/davidchappelle/bonefish-native for an example of how to define a native transport for use with bonefish. The example uses autobahn-cpp as the wamp client. Take a look at autobahn-cpp/examples/caller.cpp for an example of how to create a transport and attach a session to it.
