### ISSUE TITLE
Upgrade to websocketpp 0.7,

### ISSUE THREAD

**Issue by fabianbuettner** [tplgy/bonefish#47]
Hi,
there is a [problem](https://github.com/zaphoyd/websocketpp/issues/268) with websocketpp 0.6 that you are referencing as submodule when cross compiling for ARMv5TE. I just ran into this issue on my embedded device ...
Please update to websocketpp 0.7.

regards,
fabian büttner

**Comment by jrogers** [comment]
Upgraded in beed54a5
