### ISSUE TITLE
./daemon/bonefish，how restart

### ISSUE THREAD

**Issue by jonahzheng** [tplgy/bonefish#49]
daemon/bonefish --realm "default" --websocket-port 9999 --rawsocket-port 8888
the command run bonefish as a standalone WAMP server，
but how resart bonefish wamp server

**Comment by davidchappelle** [comment]
Just kill the daemon and run it again. There currently isn't any tooling to
run it as a daemon in the background. So whatever terminal you are running
in just kill the running daemon and relaunch it.

**Comment by davidchappelle** [comment]
You can also send it one of the termination signals:

#if defined(SIGQUIT)
    , m_termination_signals(m_io_service, SIGTERM, SIGINT, SIGQUIT)
#else
    , m_termination_signals(m_io_service, SIGTERM, SIGINT)
#endif


For example:

    kill -s [QUIT|INT|TERM] $(pgrep bonefish)

**Comment by jonahzheng** [comment]
thank you.
This is my shell script:

#/bin/bash
echo 'At stoping... '
kill -s kill  $(pgrep bonefish)
sleep 1
cd /home/bonefish-build
./daemon/bonefish --realm com.server --websocket-port 4040 --rawsocket-port 3030 >/dev/null &
echo 'restart success.'
